permalink: pretty
exclude: [node_modules]
keep_files: [assets/css, archive]
url: 
name: Applied AI Conference
description: Introducing Applied AI, the machine learning and artificial intelligence conference for developers
collections:
  videos:
    output: true
    permalink: /videos/:path/
    title: Videos

defaults:
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
  - scope:
      path: _videos/2016
    values:
      year: "2016"
  - scope:
      path: _videos/2015
    values:
      year: "2015"
